version: '3.8'
services:
        ebook:
             build: .
             container_name: do-s2-docker
             image: registry.mejik.xyz/ebook/do-s2-docker
             ports:
                     - 3040:3000
